language: cpp
sudo: false

# Build matrix:
os:
- linux
- osx
compiler:
- clang
env:
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30 PYTHON_INTERP=python2.7
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=0
matrix:
  include:
    - compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
    - bison
    - flex
    - libavcodec-dev
    - libavformat-dev
    - libavresample-dev
    - libavutil-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libode-dev
    - libopenal-dev
    - libpng-dev
    - libssl-dev
    - libswscale-dev
    - libvorbis-dev
    - libx11-dev
    - libxcursor-dev
    - libxrandr-dev
    - nvidia-cg-toolkit
    - python-dev
    - python3-dev
    - python3-pip
    - python-virtualenv
    - zlib1g-dev
    - fakeroot

before_install:
# clean up remnants of makepanda
- mv makepanda/test_imports.py .
- makepanda/selfdestruct.py --yes

install:
- >
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    ./.travis/install_macos.sh;
  else
    virtualenv --python=${PYTHON_INTERP:-python3} venv;
  fi
- source venv/bin/activate
- pip install pytest

before_script:
- mkdir built
- cd built

script:
- >
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    cmake -DHAVE_CARBON=NO -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2o_1 \
    -DBUILD_METALIBS=$BUILD_METALIBS -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT \
    -DHAVE_AUDIO=NO -DHAVE_BMP=NO -DHAVE_FFMPEG=NO -DHAVE_FFTW=NO -DHAVE_FREETYPE=NO -DHAVE_GTK2=NO -DHAVE_IMG=NO -DHAVE_JPEG=NO _DHAVE_NET=NO -DHAVE_ODE=NO -DHAVE_OPENAL=NO -DHAVE_OPENSSL=NO -DHAVE_PNG=NO -DHAVE_PNM=NO -DHAVE_SGI_RGB=NO -DHAVE_SOFTIMAGE_PIC=NO -DHAVE_SWRESAMPLE=NO -DHAVE_SWSCALE=NO -DHAVE_TGA=NO -DHAVE_X11=NO -DBUILD_PANDATOOL=NO -DPYTHON_EXECUTABLE=/usr/local/bin/python -DPYTHON_LIBRARY=/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib ..;
  else
    cmake -DHAVE_GTK2=NO -DBUILD_METALIBS=$BUILD_METALIBS \
    -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT ..;
  fi
- make -j4

- export PYTHONPATH=$PWD
- python ../test_imports.py
- pytest ../tests

# notifications:
#   irc:
#     channels:
#     - "chat.freenode.net#panda3d"
#     on_success: change
#     on_failure: always
#     use_notice: true
#     skip_join: true
